"""GET /downloads/{token} — Serve temporary files from Redis.

Files are stored by MCP tools (tabulation, auto-analyze, export) with a 5-minute TTL.
The token itself is the secret — no auth required on this endpoint.
"""

import logging

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

from config import get_settings

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Downloads"])

DOWNLOAD_TTL = 300  # 5 minutes


async def store_download(file_bytes: bytes, filename: str) -> tuple[str, str]:
    """Store file bytes in Redis for temporary download. Returns (token, download_url).

    Call this from MCP tools to make Excel files downloadable.
    """
    import uuid

    settings = get_settings()
    token = str(uuid.uuid4())
    base_url = settings.base_url or f"https://spss.insightgenius.io"
    download_url = f"{base_url}/downloads/{token}"

    try:
        import redis.asyncio as aioredis
        r = aioredis.from_url(settings.redis_url, decode_responses=False)
        await r.set(f"dl:{token}", file_bytes, ex=DOWNLOAD_TTL)
        await r.set(f"dl:name:{token}", filename.encode(), ex=DOWNLOAD_TTL)
        await r.aclose()
        logger.info("Stored download: %s (%d bytes, TTL=%ds)", filename, len(file_bytes), DOWNLOAD_TTL)
        return token, download_url
    except Exception as e:
        logger.warning("Redis unavailable for downloads: %s. Returning base64 fallback.", e)
        return "", ""


@router.get("/downloads/{token}", summary="Download temporary file",
            description="Retrieve a file generated by an MCP tool. Token expires after 5 minutes.",
            include_in_schema=False)
async def download_file(token: str):
    settings = get_settings()
    if not settings.redis_url:
        raise HTTPException(404, detail="Download service unavailable (no Redis)")

    try:
        import redis.asyncio as aioredis
        r = aioredis.from_url(settings.redis_url, decode_responses=False)
        file_bytes = await r.get(f"dl:{token}")
        filename_bytes = await r.get(f"dl:name:{token}")
        await r.aclose()
    except Exception as e:
        logger.error("Redis error on download: %s", e)
        raise HTTPException(503, detail="Download service temporarily unavailable")

    if not file_bytes:
        raise HTTPException(404, detail={
            "message": "Download link expired or invalid. Links are valid for 5 minutes after generation.",
            "hint": "Run the analysis again to get a new download link.",
        })

    filename = filename_bytes.decode() if filename_bytes else "download.xlsx"

    # Determine content type
    if filename.endswith(".xlsx"):
        media_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    elif filename.endswith(".csv"):
        media_type = "text/csv"
    elif filename.endswith(".parquet"):
        media_type = "application/octet-stream"
    else:
        media_type = "application/octet-stream"

    return Response(
        content=file_bytes,
        media_type=media_type,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "Cache-Control": "no-store",
        },
    )
